spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/invitation?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: invitation
    password: btdPpnXfa5wnSMFh
    driver-class-name: com.mysql.jdbc.Driver

wx:
  miniapp:
    configs:
      - appid: # 自己的appid
        secret: # 自己的微信secret
        token: # 自己的消息推送token
        aesKey: # 自己的消息推送aesKey
        msgDataFormat: JSON
